# Generated by Django 4.2.30 on 2026-07-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на госта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер на стая')),
                ('room_type', models.CharField(choices=[('single', 'Единична стая'), ('double', 'Двойна стая'), ('suite', 'Апартамент')], default='single', max_length=20, verbose_name='Тип стая')),
                ('capacity', models.PositiveIntegerField(verbose_name='Капацитет')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.PositiveIntegerField(default=1, verbose_name='Брой гости')),
                ('check_in', models.DateField(verbose_name='Дата на настаняване')),
                ('check_out', models.DateField(verbose_name='Дата на напускане')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.guest', verbose_name='Гост')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.room', verbose_name='Стая')),
            ],
        ),
    ]
