# Generated by Django 4.2.30 on 2026-07-02 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефонният номер трябва да съдържа само цифри и да е между 7 и 15 символа. Допуска се '+' в началото.", regex='^\\+?[0-9]{7,15}$')], verbose_name='Телефон'),
        ),
    ]
