# Generated by Django 4.2.30 on 2026-07-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0002_alter_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Цена на нощувка'),
        ),
    ]
