# Generated by Django 4.2.30 on 2026-07-03 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0003_room_price_per_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата на почистване')),
                ('is_cleaned', models.BooleanField(default=False, verbose_name='Почистена')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки от камериерката')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.room', verbose_name='Стая')),
            ],
        ),
    ]
