# Generated by Django 4.2.30 on 2026-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0004_housekeeping'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeping',
            name='cleaner_name',
            field=models.CharField(default='Дежурна камериерка', max_length=100, verbose_name='Име на камериерка'),
        ),
        migrations.AlterField(
            model_name='housekeeping',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Бележки'),
        ),
    ]
