# Generated by Django 4.2.30 on 2026-07-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0005_housekeeping_cleaner_name_alter_housekeeping_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('wine_white', 'Бяло вино (бутилка) - 20.00 лв.'), ('wine_red', 'Червено вино (бутилка) - 22.00 лв.'), ('whiskey_scot', 'Шотландско уиски (50ml) - 8.00 лв.'), ('whiskey_irish', 'Ирландско уиски (50ml) - 7.50 лв.'), ('vodka', 'Водка Премиум (50ml) - 6.00 лв.'), ('champagne', 'Шампанско (бутилка) - 25.00 лв.'), ('rakia', 'Домашна ракия (50ml) - 5.00 лв.'), ('mastika', 'Мастика (50ml) - 4.50 лв.'), ('ouzo', 'Узо (50ml) - 5.00 лв.'), ('nuts', 'Микс ядки - 5.00 лв.'), ('chocolate', 'Шоколад - 4.00 лв.'), ('pretzels', 'Солети - 1.50 лв.'), ('chips', 'Чипс Голям - 3.50 лв.'), ('juice', 'Натурален сок - 3.50 лв.'), ('water', 'Минерална вода - 2.00 лв.'), ('cola', 'Кока-Кола - 3.00 лв.'), ('fanta', 'Фанта - 3.00 лв.'), ('sprite', 'Спрайт - 3.00 лв.'), ('lemonade', 'Домашна лимонада - 4.50 лв.'), ('coffee', 'Кафе Еспресо - 2.50 лв.'), ('cappuccino', 'Капучино - 3.50 лв.'), ('tea', 'Билков чай - 2.50 лв.'), ('frappe', 'Фрапе - 4.00 лв.'), ('slice_lemon', 'Резенчета лимон - 0.10 лв.'), ('ice', 'Лед - 0.00 лв.'), ('milk', 'Прясно мляко (30ml) - 0.50 лв.'), ('ice_cream', 'Сладолед (1 топка) - 3.00 лв.'), ('cream', 'Сметана (20ml) - 0.50 лв.')], max_length=50, verbose_name='Продукт')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Час на поръчка')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.reservation', verbose_name='Резервация за стая')),
            ],
        ),
    ]
