# Generated by Django 4.2.30 on 2026-07-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0006_roomserviceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена (лв.)')),
            ],
        ),
        migrations.AlterField(
            model_name='roomserviceorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.roomserviceitem', verbose_name='Продукт'),
        ),
    ]
