# Generated by Django 4.2.30 on 2026-07-04 07:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0007_roomserviceitem_alter_roomserviceorder_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефонният номер трябва да съдържа само цифри и да е между 7 и 15 символа. Допуска се '+' в началото.", regex='^\\+?[0-9]{7,15}$')], verbose_name='Телефонен номер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена на нощувка'),
        ),
        migrations.AlterField(
            model_name='roomserviceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена (лв.)'),
        ),
    ]
